name: Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
      with:
        ruby-version: 2.6.5
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: gem install bundler -v '1.17.3'
           gem install veracode
           bundle install 
           bundle exec veracode prepare
